Repository wazuh/wazuh-puppet, pull requests merged in 2020-04, with the labels that each got.

#247 Wazuh Puppet release 3.12.2-7.6.2
  CHANGELOG.md
  VERSION
  manifests/elasticsearch.pp
  manifests/filebeat.pp
  manifests/kibana.pp
  manifests/params_agent.pp
  manifests/params_manager.pp
  manifests/wazuh_api.pp
  metadata.json
Labels: wazuhci/runtests

#249 Fixes #248 : Add option for report files changes in syscheck
  manifests/agent.pp
  manifests/params_agent.pp
  templates/fragments/_syscheck.erb
Labels: community

#242 Add strict order to audit module's tasks
  manifests/audit.pp
Labels: priority/medium, status/in-progress, type/enhancement, wazuhci/runtests

#253 Wazuh release 3.12.3 7.6.2
  CHANGELOG.md
  VERSION
  manifests/agent.pp
  manifests/audit.pp
  manifests/filebeat.pp
  manifests/kibana.pp
  manifests/manager.pp
  manifests/params_agent.pp
  manifests/params_manager.pp
  manifests/wazuh_api.pp
  metadata.json
  templates/fragments/_syscheck.erb
Labels: wazuhci/runtests
