Repository wazuh/wazuh-puppet, pull requests merged in 2020-03, with the labels that each got.

#224 Release Wazuh 3.11.4 7.6.1
  CHANGELOG.md
  VERSION
  manifests/elasticsearch.pp
  manifests/filebeat.pp
  manifests/kibana.pp
  manifests/params_agent.pp
  manifests/params_manager.pp
  manifests/wazuh_api.pp
  metadata.json
Labels: wazuhci/runtests

#212 Add a parameter ossec_rootcheck_ignore_list
  manifests/agent.pp
  manifests/manager.pp
  manifests/params_agent.pp
  manifests/params_manager.pp
  templates/fragments/_rootcheck.erb
Labels: wazuhci/runtests

#230 Upgrade to NodeJS v10
  manifests/wazuh_api.pp
  manifests/wazuh_api/nodejs.pp
Labels: wazuhci/runtests

#216 Fixes #215: Fix audit package name for Debian
  manifests/agent.pp
Labels: community

#228 Fixes #227 : Add system_audit subsection in rootcheck
  manifests/agent.pp
  manifests/params_agent.pp
  templates/fragments/_rootcheck.erb
Labels: community, enhancement

#226 Fixes #225 : Option to configure audit rules from this module itself
  manifests/agent.pp
  manifests/audit.pp
  manifests/params_agent.pp
Labels: community, enhancement

#234 Adapt active-response definition
  manifests/activeresponse.pp
  manifests/agent.pp
  manifests/manager.pp
  manifests/params_agent.pp
  manifests/params_manager.pp
  templates/fragments/_activeresponse.erb
Labels: community, enhancement

#237 Fix typo in a variable name
  manifests/manager.pp
Labels: fix

#236 Release Wazuh 3.12.0_7.6.1
  CHANGELOG.md
  VERSION
  manifests/activeresponse.pp
  manifests/agent.pp
  manifests/audit.pp
  manifests/filebeat.pp
  manifests/kibana.pp
  manifests/manager.pp
  manifests/params_agent.pp
  manifests/params_manager.pp
  manifests/wazuh_api.pp
  manifests/wazuh_api/nodejs.pp
  metadata.json
  templates/fragments/_activeresponse.erb
  templates/fragments/_rootcheck.erb
  templates/wazuh_manager.conf.erb
Labels: wazuhci/runtests
